### ISSUE TITLE
Details info

### ISSUE THREAD

**Issue by Blurayx** [OfficerKD637/skin.arctic.fuse.mod#1]
Great work with keeping AF1 updated.

would it be possible to add another option to show last aired.  similar to AF2?

AF2
<img width="610" alt="Screenshot 2024-11-23 at 2 08 34 am" src="https://github.com/user-attachments/assets/56d6e230-107c-42c7-baa8-a33a18e65b31">

AF1
<img width="552" alt="Screenshot 2024-11-23 at 2 06 55 am" src="https://github.com/user-attachments/assets/db89799d-38cc-4e21-9978-4206036b6632">

Thanks

**Comment by OfficerKD637** [comment]
Hey Blurayx!

So awesome to see you here! I am glad you're enjoying the mod!

You'll find this feature in the latest version (v0.7.43) under Skin Settings > Details > Status Date Style. 
Set it to 'Long' and it should work!

Thanks!

**Comment by Blurayx** [comment]
> Hey Blurayx!
> 
> So awesome to see you here! I am glad you're enjoying the mod!
> 
> You'll find this feature in the latest version (v0.7.43) under Skin Settings > Details > Status Date Style. Set it to 'Long' and it should work!
> 
> Thanks!

Excellent!!
Thanks  you 

As you can see, I like the S1E2 format.  jurialmunkey told me how to edit the skin Settings.xml to achieve this. Unfortunately, he has disabled this option in AF2 from V2.4.14. I do hope you’re not planning on disabling this option in AF1 🙂

<img width="671" alt="Screenshot 2024-11-24 at 4 02 54 pm" src="https://github.com/user-attachments/assets/6bc7c1cd-3c18-45e9-b5a9-3fab1a314e6e">

**Comment by OfficerKD637** [comment]
Great! Glad it worked for you!

Haha of course not. Would please mind sharing the edit so I don't inadvertently remove/mess it up while working on other features/bugs.

**Comment by Blurayx** [comment]
> Great! Glad it worked for you!
> 
> Haha of course not. Would you mind sharing the edit? -- just so I don't inadvertently remove/mess it up while working on other features/bugs haha.

<img width="865" alt="Episods" src="https://github.com/user-attachments/assets/cdb37f6e-6fac-4920-b80c-223436968c69">

I don’t know what he's changed with the new AF2 updates. Although set to "true", AF2 still displays 1x2. You may need to ask him.

**Comment by OfficerKD637** [comment]
Thank you for sharing!
