### ISSUE TITLE
Options menu

### ISSUE THREAD

**Issue by Blurayx** [OfficerKD637/skin.arctic.fuse.mod#2]
Hi Officer KD6-3.7,
The original AF1 options menu was at the bottom of the Library & Home Screen. Is there an option in AF mod to achieve this?

<img width="531" alt="Screenshot 2024-11-25 at 5 53 37 am" src="https://github.com/user-attachments/assets/a7e87d86-f8b7-4964-9f28-3f2a8a671aad">

<img width="531" alt="Screenshot 2024-11-25 at 5 53 58 am" src="https://github.com/user-attachments/assets/482a9d18-219f-4e8f-89dd-08731953aa7a">

Thanks

**Comment by OfficerKD637** [comment]
Yes, it's still there! (I haven't removed any features from the original skin haha)

You can find it under Skin Settings > Navigation and then set Content > Down to Options

**Comment by Blurayx** [comment]
Loving AF Mod

Thanks
