### ISSUE TITLE
Now Playing for IPTV EPG mode the screen turn black with no video playing in the background

### ISSUE THREAD

**Issue by aseanic** [OfficerKD637/skin.arctic.fuse.mod#3]
Comparison

This is AF Mod
![Kodi_20241129_184339](https://github.com/user-attachments/assets/f13be5b9-2f95-44eb-963c-8e9ab0d36bc6)

This is AF
![Kodi_20241129_184157](https://github.com/user-attachments/assets/24061cbf-0cbe-4f01-ba30-1dfe544001c8)

i just realized this change today, which i didnt see previously on AF Mod. Please fix this, coz kinda critical to see what on TV by browsing the EPG before clicking to full screen. Of Coz video playing just fine on fullscreen mode, but missing video on EPG mode and only audio is playing.

**Comment by OfficerKD637** [comment]
Really sorry about that. I'll push an update on Sunday to fix it.

**Comment by OfficerKD637** [comment]
Fixed in v0.7.44

Let me know if it works.

Thank you!
