### ISSUE TITLE
4K and HD Playlist.xsp like previous artic skin

### ISSUE THREAD

**Issue by aseanic** [OfficerKD637/skin.arctic.fuse.mod#4]
Jurialmunkey used to include these two xsp files in addon>skin.arctic.zephyr>extras>playlists>
which i still use for other skin of his including your arctic fuse mod. 

They allow me to widgetize the high quality and resolution with surround sound in my collection which usually 4K, HDR, Atmos and segregate them from other lower resolution perhaps more classic movie collections like these:-
 
![Screenshot 2024-12-01 085346](https://github.com/user-attachments/assets/a086a049-a8e7-4898-8bb6-4d660d070177)
_All movies in the above widgets are 4K movies_

![Screenshot 2024-12-01 085624](https://github.com/user-attachments/assets/e563b028-eb8e-400e-937e-127c97b90ff8)
_All movies in the above widgets are Lower than 4K (fhd,hd,sd)_ 

There is no other way after kodi catalogued your entire movie library could segregate them by resolution other than these two jurialmunkey xsp playlists. Which is very useful to make your widget more organized. Especially when you have movie night in your fully equipped home theater room to play the highest res movie with surround sound or just watch some old classic on a 32" TV in the bedroom.  This also will prevent duplicate thumbnails of the same movie but different resolution which will make the widget ugly.

My suggestion would be, since i have to place these two files manually everytime skin get updated (because it will be erased everytime new update) i would appreciate if they're included in the update pack. Here are the files
https://drive.google.com/file/d/12c1o6iDGkEMGEgltaWHCsxGMYZ-9BQE_/view?usp=sharing

**Comment by OfficerKD637** [comment]
That sounds cool! I have added your files in v0.7.44

Let me know if it works.

Thank you!
