### ISSUE TITLE
Show RSS news feeds - Reactivate

### ISSUE THREAD

**Issue by aseanic** [OfficerKD637/skin.arctic.fuse.mod#6]
![Screenshot 2024-12-11 185446](https://github.com/user-attachments/assets/8363096f-01c7-4838-9f17-eacb75c3dd44)
![Screenshot 2024-12-11 185351](https://github.com/user-attachments/assets/31724e05-e5ab-4eb2-abb5-ca506b84124c)
Since the RSS news is still Kodi feature, i wonder if AFmod could reactivate this beautiful marquee ticker below the page just like arctic zephyr
![Screenshot 2024-12-11 185124](https://github.com/user-attachments/assets/3371a557-d04c-4da9-a3fd-fe4657198521)
Kodi place it nicely at the very bottom of the page, perhaps on certain AFmod layout it could be implemented i.e COMBINED
I thought it's a nice feature to have since it's already there as stock kodi feature might as well make it an option to appear on the skin.

**Comment by OfficerKD637** [comment]
Yeah this is extremely simple to implement. The question is do I keep the ticker below the footer (maybe looks ugly and quite cluttered?) or only display the RSS feed when the other footers (Studio/Clock/NowPlaying on the right and Codecs & Providers/PlayCount and Dates on the left) are disabled.

I think this is a pretty niche request so I'll let you choose haha

### Option 1
![image](https://github.com/user-attachments/assets/a4345a6c-c66a-482e-9a62-5c87e13c45d0)


### Option 2
![image](https://github.com/user-attachments/assets/15de9875-6702-466e-9091-6da4bdde8a4c)

**Comment by aseanic** [comment]
Fortunately my setup layout style that i chose (COMBINED) doesnt have any "footer" only a text horizontal menu which leave a lot of space for the ticker on any page.
![image](https://github.com/user-attachments/assets/dfa452fd-5549-40db-9bc9-f5877b8ea761)

just look at how it was implemented on Arctic Zephyr, right at the bottom 
![image](https://github.com/user-attachments/assets/a43df9a6-1f1a-4a08-ae22-e513e563ba87)

I think should go for option 1 and the ticker really at the bottom of the page just like Arctic Zephyr

**Comment by OfficerKD637** [comment]
Added in v7.0.50

Enable 'RSS' under Skin Settings > Furniture > Left Footer
